version: '3.8'
services:
  cansat-postgresql:
    container_name: cansat-postgresql
    image: postgres:14.5
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - rocket-net

  rocket-rabbit-stomp:
    container_name: rocket-rabbit-stomp
    image: tronxi/rabbit-stomp
    build:
      context: ./rabbitmq/
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
    env_file: .env
    networks:
      - rocket-net


  rtmp-hls:
    container_name: rtmp-hls
    image: alqutami/rtmp-hls
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./custom_players:/usr/local/nginx/html/players
    networks:
      - rocket-net


  dashboard-backend:
    container_name: dashboard-backend
    image: dashboard_backend:0.0.6-SNAPSHOT
    ports:
       - "8070:8080"
    env_file: .env
    build:
      context: ../dashboard_backend
      dockerfile: dockerfile
    networks:
      - rocket-net

  dashboard:
    container_name: dashboard-app
#    platform: linux/amd64
    image: dashboard-app:latest
    build:
      context: ../dashboard
      dockerfile: dockerfile
    ports:
      - "80:80"
    networks:
      - rocket-net

networks:
  rocket-net: